version: '3.4'

services:
  api:
    depends_on: [dynamodb]
    build:
      context: ../LeaderboardAPI
      dockerfile: Dockerfile
  dynamodb:
    image: amazon/dynamodb-local:latest
  dynamodb-config:
    image: amazon/aws-cli
    command: dynamodb create-table --table-name leaderboard --attribute-definitions AttributeName=username,AttributeType=S AttributeName=score,AttributeType=N AttributeName=ExpiryTime,AttributeType=S --key-schema AttributeName=username,KeyType=HASH --billing-mode PAY_PER_REQUEST --endpoint-url http://dynamodb:8000
    environment:
      AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      AWS_DEFAULT_REGION: us-east-1
