version: '3.4'

services:
  api:
    depends_on: [dynamodb]
    build:
      context: ../Leaderboard.WebAPI
      dockerfile: Dockerfile
    environment:
      DYNAMO_TABLE: leaderboard
      DYNAMO_ENDPOINT: https://dynamodb:8000
      AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      AWS_DEFAULT_REGION: us-east-1
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - 8000:8000
  dynamodb-config:
    image: amazon/aws-cli
    command: dynamodb create-table --table-name leaderboard --attribute-definitions AttributeName=datetime,AttributeType=N AttributeName=score,AttributeType=N --key-schema AttributeName=datetime,KeyType=HASH AttributeName=score,KeyType=RANGE --billing-mode PAY_PER_REQUEST --endpoint-url http://dynamodb:8000
    environment:
      AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      AWS_DEFAULT_REGION: us-east-1
