name: .NET
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main

jobs:
  dotnet:
    name: Compile
    runs-on: linux
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2

      - name: Compile
        run: dotnet build --nologo -c Release

      - name: NUnit
        run: dotnet test --nologo --no-build -c Release --filter TestCategory=Unit
